### ISSUE TITLE
Camel Runtime Error with Infinispan Local Camel Producer

### ISSUE THREAD

**Issue by RHbsaunder** [rhtconsulting/fuse-quickstarts#3]
Budle deploys fine, but Camel fails to Initialize with this error.

Caused by: java.lang.IllegalArgumentException: Could not find a suitable setter for property: cacheContainer as there isn't a setter method with same type: java.lang.String nor type conversion possible: No type converter available to convert from type: java.lang.String to the required type: org.infinispan.commons.api.BasicCacheContainer with value #cacheManager
	at org.apache.camel.util.IntrospectionSupport.setProperty(IntrospectionSupport.java:561)[198:org.apache.camel.camel-core:2.15.1.redhat-620153]
	at org.apache.camel.util.IntrospectionSupport.setProperty(IntrospectionSupport.java:571)[198:org.apache.camel.camel-core:2.15.1.redhat-620153]
	at org.apache.camel.util.IntrospectionSupport.setProperties(IntrospectionSupport.java:454)[198:org.apache.camel.camel-core:2.15.1.redhat-620153]
	at org.apache.camel.util.EndpointHelper.setProperties(EndpointHelper.java:253)[198:org.apache.camel.camel-core:2.15.1.redhat-620153]
	at org.apache.camel.impl.DefaultComponent.setProperties(DefaultComponent.java:263)[198:org.apache.camel.camel-core:2.15.1.redhat-620153]
	at org.apache.camel.component.infinispan.InfinispanComponent.createEndpoint(InfinispanComponent.java:34)[279:org.apache.camel.camel-jbossdatagrid:6.5.0.Final-redhat-5]
	at org.apache.camel.impl.DefaultComponent.createEndpoint(DefaultComponent.java:114)[198:org.apache.camel.camel-core:2.15.1.redhat-620153]
	at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:558)[198:org.apache.camel.camel-core:2.15.1.redhat-620153]
	... 44 more

It appears that the Component is unable to find the Bean in the Registry or there is not a proper Setter defined.

**Comment by RHbsaunder** [comment]
Related to #4
